application: glocations507
version: 2
runtime: python27
api_version: 1
threadsafe: no
handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /.*
  script: googlemaps.py
libraries:
- name: PIL
  version: latest
- name: webob
  version: latest
- name: jinja2
  version: 2.6
- name: django
  version: 1.3